baseURL = "https://blanca-martinez19.github.io/onboardBlog/"
languageCode = "en-us"
title = "BitÃ¡cora de Viaje de Blanca"
theme = "hugo-winston-theme"
relativeURLs = true
canonifyURLs = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[params]
  google_analytics_id = ""
  # Hey Explorer aquÃ­ pon tu twitter ðŸ‘‡
  twitter_handle = "@visual_partner"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addFrame = true
  addDot = true
